<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Tienda Online</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        header {
            background-color: #333;
            color: #fff;
            padding: 10px 0;
            text-align: center;
        }
        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
        }
        .product {
            background: #fff;
            margin: 20px 0;
            padding: 20px;
            border: 1px solid #ddd;
        }
        .product img {
            max-width: 100%;
        }
        .product h2 {
            margin: 0;
        }
        .product p {
            font-size: 1.2em;
        }
        .product .price {
            font-size: 1.5em;
            color: #333;
        }
        .product button {
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px;
            cursor: pointer;
        }
        .product button:hover {
            background-color: #555;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>Mi Tienda Online</h1>
        </div>
    </header>
    <div class="container">
        <div class="product">
            <img src="https://via.placeholder.com/300" alt="Producto 1">
            <h2>Producto 1</h2>
            <p>Descripción breve del producto.</p>
            <p class="price">€10.00</p>
            <button>Agregar al carrito</button>
        </div>
        <div class="product">
            <img src="https://via.placeholder.com/300" alt="Producto 2">
            <h2>Producto 2</h2>
            <p>Descripción breve del producto.</p>
            <p class="price">€20.00</p>
            <button>Agregar al carrito</button>
        </div>
    </div>
</body>
</html>
